/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KUEH;

/**
 *
 * @author A S U S
 */
    
import static KUEH.stt.executeQuery;
import KUEH.username;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.*;
import jdk.nashorn.internal.runtime.regexp.joni.Config;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.EventListener;
import net.proteanit.sql.DbUtils;
import javax.swing.table.*;
import java.lang.NullPointerException;

public class INPUT extends javax.swing.JFrame {

    public MENU MENU;
    public INPUT INPUT;
    private Connection con;
    private Statement stt;
    private ResultSet rss;
    private PreparedStatement ppt;
    
    //tabel
    private Connection conn;
    private Statement stat;
    private ResultSet res;
    private PreparedStatement pppt;
    

    //umur
    private Connection conn1;
    private Statement stat1;
    private ResultSet res1;
    private PreparedStatement pppt1;
    
    //hapus
    private Connection conh;
    private Statement stath;
    private ResultSet resh;
    private PreparedStatement ppth;
    
    //Edit
    private Connection cone;
    private Statement state;
    private ResultSet rese;
    private PreparedStatement ppte;
    
    
    
    
    public INPUT() {
        initComponents();
        hapusdbs.setEnabled(false);
        update.setEnabled(false);
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
            stt = con.createStatement();
            statusi.setText("AKTIF");
            statusi.setForeground(Color.green);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
            statusi.setText("TIDAK AKTIF");
            statusi.setForeground(Color.red);
        }
        tampiltabelinput();
               
        
    }
   
  
    
    
    
  void tampiltabelinput(){
    DefaultTableModel tb= new DefaultTableModel();
// Memberi nama pada setiap kolom tabel
    tb.addColumn("NIK");
    tb.addColumn("No KK");
    tb.addColumn("Nama");
    tb.addColumn("Umur");
    tb.addColumn("L / P");
    tb.addColumn("Tahun Lahir");
    tb.addColumn("Dusun");
    tb.addColumn("No HP");
    tabel.setModel(tb);

try{
// Mengambil data dari database
   Class.forName("com.mysql.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
   stt = con.createStatement();
   
   res = stt.executeQuery("SELECT * FROM datagampongkueh");
   
   
   conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
   stat1 = conn1.createStatement();
   res1 = stat1.executeQuery("SELECT *, YEAR(CURRENT_DATE()) - TLAHIR AS UMUR FROM datagampongkueh");


    

while (res.next()&& res1.next())
{
// Mengambil data dari database berdasarkan nama kolom pada tabel
// Lalu di tampilkan ke dalam JTable
tb.addRow(new Object[]{
res.getString("NIK"),
res.getString("NOKK"),
res.getString("NAMA"),
res1.getString("UMUR"),
res.getString("GENDER"),
res.getInt("TLAHIR"),
res.getString("DUSUN"),
res.getString("NOHP")
});

}

}catch (Exception e){
}

}
    
    
        void bersih() {
    
        inputkk.setText("");
        inputnik.setText("");
        inputnama.setText("");
        inputdusun.setText("");
        inputhp.setText("");
        inputtahun.setText("");
        ceklk.setSelected(false);
        cekpr.setSelected(false);
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        inputkk = new javax.swing.JTextField();
        inputnik = new javax.swing.JTextField();
        inputnama = new javax.swing.JTextField();
        inputhp = new javax.swing.JTextField();
        inputdusun = new javax.swing.JTextField();
        ceklk = new javax.swing.JCheckBox();
        cekpr = new javax.swing.JCheckBox();
        okinput = new javax.swing.JButton();
        inputcari = new javax.swing.JTextField();
        okcari = new javax.swing.JButton();
        carisemua = new javax.swing.JCheckBox();
        caripr = new javax.swing.JCheckBox();
        carilk = new javax.swing.JCheckBox();
        hapusdbs = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        inputtahun = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        statusi = new javax.swing.JLabel();
        fres = new javax.swing.JButton();
        aktifh = new javax.swing.JCheckBox();
        update = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "No KK", "Nama", "Umur", "L / P", "Tahun Lahir", "Dusun", "No HP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabel.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tabel.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabel.getColumnModel().getColumn(2).setResizable(false);
            tabel.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabel.getColumnModel().getColumn(3).setResizable(false);
            tabel.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabel.getColumnModel().getColumn(4).setResizable(false);
            tabel.getColumnModel().getColumn(4).setPreferredWidth(3);
            tabel.getColumnModel().getColumn(5).setResizable(false);
            tabel.getColumnModel().getColumn(6).setResizable(false);
            tabel.getColumnModel().getColumn(6).setPreferredWidth(80);
            tabel.getColumnModel().getColumn(7).setResizable(false);
            tabel.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NIK");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NO KK");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NAMA ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tahun Lahir ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Dusun ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("No HP ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText(":");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText(":");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(":");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText(":");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText(":");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText(":");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText(":");

        inputkk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputkk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputkkActionPerformed(evt);
            }
        });

        inputnik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        inputnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        inputhp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        inputdusun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ceklk.setText("Laki - Laki");
        ceklk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceklkActionPerformed(evt);
            }
        });

        cekpr.setText("Perempuan");
        cekpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekprActionPerformed(evt);
            }
        });

        okinput.setBackground(new java.awt.Color(102, 255, 102));
        okinput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okinput.setText("INPUT");
        okinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okinputActionPerformed(evt);
            }
        });

        inputcari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        okcari.setBackground(new java.awt.Color(51, 255, 204));
        okcari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okcari.setText("?");
        okcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okcariActionPerformed(evt);
            }
        });

        carisemua.setSelected(true);
        carisemua.setText("Semua");
        carisemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carisemuaActionPerformed(evt);
            }
        });

        caripr.setText("Perempuan");
        caripr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariprActionPerformed(evt);
            }
        });

        carilk.setText("Laki Laki");
        carilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carilkActionPerformed(evt);
            }
        });

        hapusdbs.setBackground(new java.awt.Color(255, 51, 51));
        hapusdbs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hapusdbs.setText("HAPUS");
        hapusdbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusdbsActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Note : ");

        jLabel16.setText("Silahkan Select / Pilih Dulu Sebelum Di  EDIT / HAPUS");

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        inputtahun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setText("STATUS : ");

        statusi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusi.setForeground(new java.awt.Color(255, 0, 0));

        fres.setBackground(new java.awt.Color(255, 255, 51));
        fres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fres.setText("LOAD");
        fres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fresActionPerformed(evt);
            }
        });

        aktifh.setText("Aktifkan Tombol Menghapus");
        aktifh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktifhActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 0, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("SMS Gampong");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenuItem3.setText("Exit Total");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Service");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Koneksi Ulang");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hapusdbs, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(aktifh))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(fres, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(okinput, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(update)
                                .addGap(30, 30, 30)
                                .addComponent(inputcari, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(okcari)))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputkk, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputnama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputdusun, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputhp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(ceklk)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                        .addComponent(cekpr)
                                        .addGap(14, 14, 14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(carisemua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carilk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caripr)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputtahun, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputnik, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputnik, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputkk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inputnama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(ceklk)
                        .addComponent(cekpr))
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputtahun)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(inputdusun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(inputhp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carisemua)
                    .addComponent(caripr)
                    .addComponent(carilk))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputcari)
                    .addComponent(okcari)
                    .addComponent(okinput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addComponent(fres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapusdbs)
                            .addComponent(aktifh))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputkkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputkkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputkkActionPerformed

    private void carilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carilkActionPerformed
        // TODO add your handling code here:
        C = "L";
        carisemua.setSelected(false);
        caripr.setSelected(false);
    }//GEN-LAST:event_carilkActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
               MENU m = new MENU();
                m.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
                LOGIN m = new LOGIN();
                m.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void okinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okinputActionPerformed
        try {
            // TODO add your handling code here:
            
           Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
            stt = con.createStatement();
            stt.executeUpdate("INSERT INTO datagampongkueh VALUES('"+inputnik.getText()+"','"+inputkk.getText()+"','"+inputnama.getText()+"','"+jk+"','"+inputtahun.getText()+"','"+inputdusun.getText()+"','"+inputhp.getText()+"')");
            
            JOptionPane.showMessageDialog(null,"Sukses");
            tampiltabelinput();
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Sudah Terdaftar Atau Ada yang Kosong");
        }
        
    }//GEN-LAST:event_okinputActionPerformed

    private void ceklkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceklkActionPerformed
        // TODO add your handling code here:
        jk = "L";
        cekpr.setSelected(false);
    }//GEN-LAST:event_ceklkActionPerformed

    private void cekprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekprActionPerformed
        // TODO add your handling code here:
        jk = "P";
        ceklk.setSelected(false);
    }//GEN-LAST:event_cekprActionPerformed

    private void hapusdbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusdbsActionPerformed
        // TODO add your handling code here:
        
        int baris = tabel.getSelectedRow();
        String cell = tabel.getModel().getValueAt(baris, 0).toString();
        String SQLH = "DELETE FROM datagampongkueh WHERE NIK = " + cell;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conh = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
            ppth = conh.prepareStatement(SQLH);
            ppth.execute();
            JOptionPane.showMessageDialog(null, "Sukses Menghapus Database");
            tampiltabelinput();
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        } finally {
            try {
                ppth.close();
                
            } catch (Exception e) {
                
            }
        }
        
    }//GEN-LAST:event_hapusdbsActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
          try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
            stt = con.createStatement();
            JOptionPane.showMessageDialog(null,"Koneksi Berhasil");
            statusi.setText("AKTIF");
        
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
            statusi.setText("TIDAK AKTIF");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void fresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fresActionPerformed
        // TODO add your handling code here:
        tampiltabelinput();
    }//GEN-LAST:event_fresActionPerformed

    private void aktifhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktifhActionPerformed
        // TODO add your handling code here:
        if (aktifh.isSelected()) {
            hapusdbs.setEnabled(true);
        }
        else {
            hapusdbs.setEnabled(false);
        }
    }//GEN-LAST:event_aktifhActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
        inputnik.setText(tabel.getValueAt(baris, 0).toString());
        inputkk.setText(tabel.getValueAt(baris, 1).toString());
        inputnama.setText(tabel.getValueAt(baris, 2).toString());
        inputtahun.setText(tabel.getValueAt(baris, 5).toString());
        inputdusun.setText(tabel.getValueAt(baris, 6).toString());
        inputhp.setText(tabel.getValueAt(baris, 7).toString());
        update.setEnabled(true);
        okinput.setEnabled(false);
        
        
           
      
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cone = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");           
            String SQLE = "UPDATE datagampongkueh SET NIK='"+inputnik.getText()+"',NOKK='"+inputkk.getText()+"',NAMA='"+inputnama.getText()+"',GENDER='"+jk+"',TLAHIR='"+inputtahun.getText()+"',DUSUN='"+inputdusun.getText()+"',NOHP='"+inputhp.getText()+"' WHERE NIK='"+inputnik.getText()+"'";
            ppte = cone.prepareStatement(SQLE);
            ppte.execute();
            JOptionPane.showMessageDialog(null, "Sukses Mengedit Database");
            tampiltabelinput();
            okinput.setEnabled(true);
            bersih();
            update.setEnabled(false);
            
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_updateActionPerformed

    private void carisemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carisemuaActionPerformed
        // TODO add your handling code here:
        C = "S";
        carilk.setSelected(false);
        caripr.setSelected(false);
    }//GEN-LAST:event_carisemuaActionPerformed

    private void cariprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariprActionPerformed
        // TODO add your handling code here:
        C = "P";
        carisemua.setSelected(false);
        carilk.setSelected(false);
    }//GEN-LAST:event_cariprActionPerformed

    private void okcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okcariActionPerformed
        // TODO add your handling code here:
        if (C == "L") {
            tabelcarijk();
        }
        else if (C == "P") {
            tabelcarijk();
        }
        else {
         
            tabelcarisemua();
      
        }
        inputcari.setText("");
    }//GEN-LAST:event_okcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INPUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INPUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INPUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INPUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INPUT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox carilk;
    private javax.swing.JCheckBox caripr;
    private javax.swing.JCheckBox carisemua;
    private javax.swing.JCheckBox ceklk;
    private javax.swing.JCheckBox cekpr;
    private javax.swing.JButton fres;
    private javax.swing.JButton hapusdbs;
    private javax.swing.JTextField inputcari;
    private javax.swing.JTextField inputdusun;
    private javax.swing.JTextField inputhp;
    private javax.swing.JTextField inputkk;
    private javax.swing.JTextField inputnama;
    private javax.swing.JTextField inputnik;
    private javax.swing.JTextField inputtahun;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton okcari;
    private javax.swing.JButton okinput;
    private javax.swing.JLabel statusi;
    private javax.swing.JTable tabel;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
    
    public String jk;
    public String C;
    
    
    
     void tabelcarijk(){
    DefaultTableModel tb= new DefaultTableModel();
// Memberi nama pada setiap kolom tabel
    tb.addColumn("NIK");
    tb.addColumn("No KK");
    tb.addColumn("Nama");
    tb.addColumn("Umur");
    tb.addColumn("L / P");
    tb.addColumn("Tahun Lahir");
    tb.addColumn("Dusun");
    tb.addColumn("No HP");
    tabel.setModel(tb);

try{
// Mengambil data dari database
   Class.forName("com.mysql.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
   stt = con.createStatement();
   
   res = stt.executeQuery("SELECT * FROM datagampongkueh WHERE NAMA like '%" +inputcari.getText()+ "%'" + " and GENDER like '%" +C+ "%' ");
   
   
   conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
   stat1 = conn1.createStatement();
   res1 = stat1.executeQuery("SELECT *, YEAR(CURRENT_DATE()) - TLAHIR AS UMUR FROM datagampongkueh");


    

while (res.next()&& res1.next())
{
// Mengambil data dari database berdasarkan nama kolom pada tabel
// Lalu di tampilkan ke dalam JTable
tb.addRow(new Object[]{
res.getString("NIK"),
res.getString("NOKK"),
res.getString("NAMA"),
res1.getString("UMUR"),
res.getString("GENDER"),
res.getInt("TLAHIR"),
res.getString("DUSUN"),
res.getString("NOHP")
});

}

}catch (Exception e){
}

}
  
     void tabelcarisemua(){
    DefaultTableModel tb= new DefaultTableModel();
// Memberi nama pada setiap kolom tabel
    tb.addColumn("NIK");
    tb.addColumn("No KK");
    tb.addColumn("Nama");
    tb.addColumn("Umur");
    tb.addColumn("L / P");
    tb.addColumn("Tahun Lahir");
    tb.addColumn("Dusun");
    tb.addColumn("No HP");
    tabel.setModel(tb);

try{
// Mengambil data dari database
   Class.forName("com.mysql.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
   stt = con.createStatement();
   
   res = stt.executeQuery("SELECT * FROM datagampongkueh WHERE NAMA like '%" +inputcari.getText()+ "%'");
   
   
   conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
   stat1 = conn1.createStatement();
   res1 = stat1.executeQuery("SELECT *, YEAR(CURRENT_DATE()) - TLAHIR AS UMUR FROM datagampongkueh");


    

while (res.next()&& res1.next())
{
// Mengambil data dari database berdasarkan nama kolom pada tabel
// Lalu di tampilkan ke dalam JTable
tb.addRow(new Object[]{
res.getString("NIK"),
res.getString("NOKK"),
res.getString("NAMA"),
res1.getString("UMUR"),
res.getString("GENDER"),
res.getInt("TLAHIR"),
res.getString("DUSUN"),
res.getString("NOHP")
});

}

}catch (Exception e){
}

}
     
}
