/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KUEH;

/**
 *
 * @author A S U S
 */
import static KUEH.stt.executeQuery;
import KUEH.username;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.*;
import jdk.nashorn.internal.runtime.regexp.joni.Config;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.EventListener;
import net.proteanit.sql.DbUtils;
import javax.swing.table.*;
import java.lang.NullPointerException;

public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    
    public MENU MENU;
    public INPUT INPUT;
    private Connection con;
    private Statement stt;
    
    public MENU() {
      
        initComponents(); 
        disableorang();
        disablerame();
         DefaultTableModel tb= new DefaultTableModel();
           tb.addColumn("Tanggal");
           tb.addColumn("No HP");
           tb.addColumn("Status");
           tb.addColumn("Pesan");
           tabelrame.setModel(tb);
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
            stt = con.createStatement();
            statuss.setText("AKTIF");
            statuss.setForeground(Color.green);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
            statuss.setText("TIDAK AKTIF");
            statuss.setForeground(Color.red);
        }
         
    }
    
  void disableorang() {
      hpsendiri.setEditable(false);
      pesansendiri.setEditable(false);
      hapushpsendiri.setEnabled(false);
      hapuspesansendiri.setEnabled(false);
      kirimsendiri.setEnabled(false);
      
  } 
  
  void enableorang() {
      hpsendiri.setEditable(true);
      pesansendiri.setEditable(true);
      hapushpsendiri.setEnabled(true);
      hapuspesansendiri.setEnabled(true);
      kirimsendiri.setEnabled(true);
      
  }
  
  void disablerame() {
      loadrame.setEnabled(false);
      pesanrame.setEditable(false);
      rapatrame.setEnabled(false);
      kematianrame.setEnabled(false);
      costumrame.setEnabled(false);
      semuarame.setEnabled(false);
      pemudarame.setEnabled(false);
      tuharame.setEnabled(false);
      lakirame.setEnabled(false);
      perempuanrame.setEnabled(false);
      tabelrame.setEnabled(false);
      kirimrame.setEnabled(false);
      rapatpemudarame.setEnabled(false);
      rapattuharame.setEnabled(false);
      drahrame.setEnabled(false);
      
  }
  
  void enablerame() {
      loadrame.setEnabled(true);
      pesanrame.setEditable(true);
      rapatrame.setEnabled(true);
      kematianrame.setEnabled(true);
      costumrame.setEnabled(true);
      semuarame.setEnabled(true);
      pemudarame.setEnabled(true);
      tuharame.setEnabled(true);
      lakirame.setEnabled(true);
      perempuanrame.setEnabled(true);
      tabelrame.setEnabled(true);
      kirimrame.setEnabled(true);
      rapatpemudarame.setEnabled(true);
      rapattuharame.setEnabled(true);
      drahrame.setEnabled(true);
      
  }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        statuss = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pesanmasuk = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelmasuk = new javax.swing.JTable();
        hapusmasuk = new javax.swing.JButton();
        bacamasuk = new javax.swing.JButton();
        loadmasuk = new javax.swing.JButton();
        orang = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hpsendiri = new javax.swing.JTextField();
        hapuspesansendiri = new javax.swing.JButton();
        kirimsendiri = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        pesansendiri = new javax.swing.JTextArea();
        hapushpsendiri = new javax.swing.JButton();
        sendiri = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelrame = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        pesanrame = new javax.swing.JTextArea();
        kirimrame = new javax.swing.JButton();
        semuarame = new javax.swing.JCheckBox();
        pemudarame = new javax.swing.JCheckBox();
        tuharame = new javax.swing.JCheckBox();
        perempuanrame = new javax.swing.JCheckBox();
        lakirame = new javax.swing.JCheckBox();
        rapatrame = new javax.swing.JCheckBox();
        loadrame = new javax.swing.JButton();
        rapatpemudarame = new javax.swing.JCheckBox();
        rapattuharame = new javax.swing.JCheckBox();
        kematianrame = new javax.swing.JCheckBox();
        costumrame = new javax.swing.JCheckBox();
        drahrame = new javax.swing.JCheckBox();
        rame = new javax.swing.JCheckBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SMS Gampong");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("SMS  GATEWAY");

        jLabel5.setText("STATUS :");

        statuss.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statuss.setForeground(new java.awt.Color(204, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("PESAN MASUK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pesanmasuk.setEditable(false);
        pesanmasuk.setColumns(20);
        pesanmasuk.setRows(5);
        jScrollPane1.setViewportView(pesanmasuk);

        tabelmasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal", "Nomor", "Isi Pesan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelmasuk);
        if (tabelmasuk.getColumnModel().getColumnCount() > 0) {
            tabelmasuk.getColumnModel().getColumn(2).setHeaderValue("Isi Pesan");
        }

        hapusmasuk.setBackground(new java.awt.Color(255, 51, 51));
        hapusmasuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hapusmasuk.setText("HAPUS");

        bacamasuk.setBackground(new java.awt.Color(0, 255, 51));
        bacamasuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bacamasuk.setText("BACA");

        loadmasuk.setBackground(new java.awt.Color(255, 255, 102));
        loadmasuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loadmasuk.setText("LOAD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hapusmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(loadmasuk)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bacamasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hapusmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bacamasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        orang.setBackground(new java.awt.Color(153, 153, 153));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("KIRIM PERORANGAN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NO HP        :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ISI PESAN :");

        hpsendiri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        hapuspesansendiri.setBackground(new java.awt.Color(255, 102, 102));
        hapuspesansendiri.setText("X");
        hapuspesansendiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapuspesansendiriActionPerformed(evt);
            }
        });

        kirimsendiri.setBackground(new java.awt.Color(102, 255, 102));
        kirimsendiri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kirimsendiri.setText("KIRIM");

        pesansendiri.setColumns(20);
        pesansendiri.setRows(5);
        jScrollPane4.setViewportView(pesansendiri);

        hapushpsendiri.setBackground(new java.awt.Color(255, 102, 102));
        hapushpsendiri.setText("X");
        hapushpsendiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapushpsendiriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orangLayout = new javax.swing.GroupLayout(orang);
        orang.setLayout(orangLayout);
        orangLayout.setHorizontalGroup(
            orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orangLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orangLayout.createSequentialGroup()
                                .addComponent(hapuspesansendiri)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orangLayout.createSequentialGroup()
                                .addGap(0, 106, Short.MAX_VALUE)
                                .addComponent(kirimsendiri, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(orangLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(hpsendiri, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hapushpsendiri)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        orangLayout.setVerticalGroup(
            orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangLayout.createSequentialGroup()
                .addGroup(orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orangLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(hpsendiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapushpsendiri))
                        .addGroup(orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orangLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hapuspesansendiri))
                            .addGroup(orangLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel6))))
                    .addGroup(orangLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kirimsendiri, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sendiri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sendiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendiriActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("INFO PENGUMUMAN");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ISI PESAN :");

        tabelrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "No HP", "Status", "Pesan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabelrame);

        pesanrame.setColumns(20);
        pesanrame.setRows(5);
        jScrollPane6.setViewportView(pesanrame);

        kirimrame.setBackground(new java.awt.Color(102, 255, 102));
        kirimrame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kirimrame.setText("KIRIM");

        semuarame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        semuarame.setText("SEMUA");
        semuarame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semuarameActionPerformed(evt);
            }
        });

        pemudarame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pemudarame.setText("PEMUDA");
        pemudarame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemudarameActionPerformed(evt);
            }
        });

        tuharame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tuharame.setText("TUHA");
        tuharame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuharameActionPerformed(evt);
            }
        });

        perempuanrame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        perempuanrame.setText("PEREMPUAN");
        perempuanrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanrameActionPerformed(evt);
            }
        });

        lakirame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lakirame.setText("LAKI");
        lakirame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakirameActionPerformed(evt);
            }
        });

        rapatrame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rapatrame.setText("RAPAT UMUM");
        rapatrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapatrameActionPerformed(evt);
            }
        });

        loadrame.setBackground(new java.awt.Color(255, 255, 102));
        loadrame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loadrame.setText("LOAD");
        loadrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadrameActionPerformed(evt);
            }
        });

        rapatpemudarame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rapatpemudarame.setText("RAPAT PEMUDA");
        rapatpemudarame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapatpemudarameActionPerformed(evt);
            }
        });

        rapattuharame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rapattuharame.setText("RAPAT TUHA");
        rapattuharame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapattuharameActionPerformed(evt);
            }
        });

        kematianrame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kematianrame.setText("KEMATIAN");
        kematianrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kematianrameActionPerformed(evt);
            }
        });

        costumrame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        costumrame.setText("COSTUM");
        costumrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costumrameActionPerformed(evt);
            }
        });

        drahrame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        drahrame.setText("DRAH");
        drahrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drahrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rapatrame)
                                    .addComponent(rapatpemudarame)
                                    .addComponent(rapattuharame))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(semuarame)
                                .addGap(18, 18, 18)
                                .addComponent(pemudarame)
                                .addGap(18, 18, 18)
                                .addComponent(tuharame)
                                .addGap(18, 18, 18)
                                .addComponent(lakirame)
                                .addGap(18, 18, 18)
                                .addComponent(perempuanrame)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kematianrame)
                            .addComponent(drahrame)
                            .addComponent(costumrame)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kirimrame)))
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadrame)
                .addGap(80, 80, 80)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rapatrame)
                                    .addComponent(drahrame))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rapatpemudarame)
                                    .addComponent(kematianrame))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rapattuharame)
                                    .addComponent(costumrame)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(loadrame, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)))
                .addGap(20, 28, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perempuanrame)
                    .addComponent(lakirame)
                    .addComponent(tuharame)
                    .addComponent(pemudarame)
                    .addComponent(semuarame))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kirimrame, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        rame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rameActionPerformed(evt);
            }
        });

        jMenu6.setText("Menu");

        jMenuItem2.setText("Input / Edit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);
        jMenu6.add(jSeparator2);

        jMenuItem3.setText("Hapus Semua Inbox");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);
        jMenu6.add(jSeparator3);

        jMenuItem4.setText("Logout");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);
        jMenu6.add(jSeparator4);

        jMenuItem5.setText("Exit Total");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);
        jMenu6.add(jSeparator1);

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar2.add(jMenu6);

        jMenu1.setText("Service");

        jMenuItem6.setText("Koneksi Ulang");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendiri, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rame, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statuss, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(orang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(statuss, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(sendiri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rame)
                        .addGap(153, 153, 153)))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
                LOGIN m = new LOGIN();
                m.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Aplikasi SMS Gampong\n"+"Powered By Jotii\n"+"Contact : Prajuritn@gmail.com\n"+"Copyright : Ro-Ti Project\n"+"2018 - 2019");
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        INPUT i = new INPUT();
                i.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datasms" , "root" , "");
            stt = con.createStatement();
            JOptionPane.showMessageDialog(null,"Koneksi Berhasil");
            statuss.setText("AKTIF");
        
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
            statuss.setText("TIDAK AKTIF");
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void sendiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendiriActionPerformed
        // TODO add your handling code here:
        rame.setSelected(false);
        if (sendiri.isSelected()) {
            enableorang();
            disablerame();
        }
        else {
            
            disableorang();
            hpsendiri.setText("");
            pesansendiri.setText("");
        }
        
        
    }//GEN-LAST:event_sendiriActionPerformed

    private void rameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rameActionPerformed
        // TODO add your handling code here:
        sendiri.setSelected(false);
       if (rame.isSelected()) {
            enablerame();
            disableorang();
        }
       else {
           disablerame();
           semuarame.setSelected(false);
           pemudarame.setSelected(false);
           tuharame.setSelected(false);
           lakirame.setSelected(false);
           perempuanrame.setSelected(false);
           rapatrame.setSelected(false);
           rapatpemudarame.setSelected(false);
           rapattuharame.setSelected(false);
           drahrame.setSelected(false);
           kematianrame.setSelected(false);
           costumrame.setSelected(false);
          
       }
        
    }//GEN-LAST:event_rameActionPerformed

    private void hapushpsendiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapushpsendiriActionPerformed
        // TODO add your handling code here:
        hpsendiri.setText("");
    }//GEN-LAST:event_hapushpsendiriActionPerformed

    private void hapuspesansendiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapuspesansendiriActionPerformed
        // TODO add your handling code here:
        pesansendiri.setText("");
    }//GEN-LAST:event_hapuspesansendiriActionPerformed

    private void semuarameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semuarameActionPerformed
        // TODO add your handling code here:
        pemudarame.setSelected(false);
        tuharame.setSelected(false);
        lakirame.setSelected(false);
        perempuanrame.setSelected(false);
    }//GEN-LAST:event_semuarameActionPerformed

    private void pemudarameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemudarameActionPerformed
        // TODO add your handling code here:
        semuarame.setSelected(false);
        tuharame.setSelected(false);
        lakirame.setSelected(false);
        perempuanrame.setSelected(false);
        
    }//GEN-LAST:event_pemudarameActionPerformed

    private void tuharameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuharameActionPerformed
        // TODO add your handling code here:
        semuarame.setSelected(false);
        pemudarame.setSelected(false);
        lakirame.setSelected(false);
        perempuanrame.setSelected(false);
    }//GEN-LAST:event_tuharameActionPerformed

    private void lakirameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakirameActionPerformed
        // TODO add your handling code here:
        semuarame.setSelected(false);
        pemudarame.setSelected(false);
        tuharame.setSelected(false);
        perempuanrame.setSelected(false);
    }//GEN-LAST:event_lakirameActionPerformed

    private void perempuanrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanrameActionPerformed
        // TODO add your handling code here:
        semuarame.setSelected(false);
        pemudarame.setSelected(false);
        lakirame.setSelected(false);
        tuharame.setSelected(false);
    }//GEN-LAST:event_perempuanrameActionPerformed

    private void rapatrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapatrameActionPerformed
        // TODO add your handling code here:
           
           rapatpemudarame.setSelected(false);
           rapattuharame.setSelected(false);
           drahrame.setSelected(false);
           kematianrame.setSelected(false);
           costumrame.setSelected(false);
           
        if(rapatrame.isSelected()) {
            pesanrame.setText("ini adalah rapat umum");
        }
        else {
            pesanrame.setText("");
        }
    }//GEN-LAST:event_rapatrameActionPerformed

    private void rapatpemudarameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapatpemudarameActionPerformed
        // TODO add your handling code here:
           rapatrame.setSelected(false);
           rapattuharame.setSelected(false);
           drahrame.setSelected(false);
           kematianrame.setSelected(false);
           costumrame.setSelected(false);
        
        if(rapatpemudarame.isSelected()) {
            pesanrame.setText("ini adalah rapat pemuda");
        }
        else {
            pesanrame.setText("");
        }
    }//GEN-LAST:event_rapatpemudarameActionPerformed

    private void rapattuharameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapattuharameActionPerformed
        // TODO add your handling code here:
           rapatrame.setSelected(false);
           rapatpemudarame.setSelected(false);
           drahrame.setSelected(false);
           kematianrame.setSelected(false);
           costumrame.setSelected(false);
           if (rapattuharame.isSelected()) {
               pesanrame.setText("ini adalah rapat ureung tuha");
           }
           else {
               pesanrame.setText("");
           }
    }//GEN-LAST:event_rapattuharameActionPerformed

    private void drahrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drahrameActionPerformed
        // TODO add your handling code here:
           rapatrame.setSelected(false);
           rapatpemudarame.setSelected(false);
           rapattuharame.setSelected(false);
           kematianrame.setSelected(false);
           costumrame.setSelected(false);
           if (drahrame.isSelected()) {
               pesanrame.setText("Ini Adalah Drah");
           }
           else {
               pesanrame.setText("");
           }
    }//GEN-LAST:event_drahrameActionPerformed

    private void kematianrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kematianrameActionPerformed
        // TODO add your handling code here:
           rapatrame.setSelected(false);
           rapatpemudarame.setSelected(false);
           rapattuharame.setSelected(false);
           drahrame.setSelected(false);
           costumrame.setSelected(false);
           if (kematianrame.isSelected()) {
               pesanrame.setText("Ini adalah pesan Kematian");
           }
           else {
               pesanrame.setText("");
           }
    }//GEN-LAST:event_kematianrameActionPerformed

    private void costumrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costumrameActionPerformed
        // TODO add your handling code here:
           rapatrame.setSelected(false);
           rapatpemudarame.setSelected(false);
           rapattuharame.setSelected(false);
           drahrame.setSelected(false);
           kematianrame.setSelected(false);
           if (costumrame.isSelected()) {
               pesanrame.setText("");
           }
           else {
               pesanrame.setText("");
           }
    }//GEN-LAST:event_costumrameActionPerformed

    private void loadrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadrameActionPerformed
        // TODO add your handling code here:
           semuarame.setSelected(false);
           pemudarame.setSelected(false);
           tuharame.setSelected(false);
           lakirame.setSelected(false);
           perempuanrame.setSelected(false);
           rapatrame.setSelected(false);
           rapatpemudarame.setSelected(false);
           rapattuharame.setSelected(false);
           drahrame.setSelected(false);
           kematianrame.setSelected(false);
           costumrame.setSelected(false);
           pesanrame.setText("");
           DefaultTableModel tb= new DefaultTableModel();
           tb.addColumn("Tanggal");
           tb.addColumn("No HP");
           tb.addColumn("Status");
           tb.addColumn("Pesan");
           tabelrame.setModel(tb);
    }//GEN-LAST:event_loadrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bacamasuk;
    private javax.swing.JCheckBox costumrame;
    private javax.swing.JCheckBox drahrame;
    private javax.swing.JButton hapushpsendiri;
    private javax.swing.JButton hapusmasuk;
    private javax.swing.JButton hapuspesansendiri;
    private javax.swing.JTextField hpsendiri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JCheckBox kematianrame;
    private javax.swing.JButton kirimrame;
    private javax.swing.JButton kirimsendiri;
    private javax.swing.JCheckBox lakirame;
    private javax.swing.JButton loadmasuk;
    private javax.swing.JButton loadrame;
    private javax.swing.JPanel orang;
    private javax.swing.JCheckBox pemudarame;
    private javax.swing.JCheckBox perempuanrame;
    private javax.swing.JTextArea pesanmasuk;
    private javax.swing.JTextArea pesanrame;
    private javax.swing.JTextArea pesansendiri;
    private javax.swing.JCheckBox rame;
    private javax.swing.JCheckBox rapatpemudarame;
    private javax.swing.JCheckBox rapatrame;
    private javax.swing.JCheckBox rapattuharame;
    private javax.swing.JCheckBox semuarame;
    private javax.swing.JCheckBox sendiri;
    private javax.swing.JLabel statuss;
    private javax.swing.JTable tabelmasuk;
    private javax.swing.JTable tabelrame;
    private javax.swing.JCheckBox tuharame;
    // End of variables declaration//GEN-END:variables
}
